source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'HGSegmentedPageViewController_Example' do
  pod 'HGSegmentedPageViewController', :path => '../'
  
  target 'HGSegmentedPageViewController_Tests' do
    inherit! :search_paths

  end
end
