use_frameworks!

platform :ios, '8.0'

target 'HGSegmentedPageViewController_Example' do
  pod 'HGSegmentedPageViewController', :path => '../'

  target 'HGSegmentedPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
